### ISSUE TITLE
Delet the contacts

### ISSUE THREAD

**Issue by moh1122** [geowarsong/ContactMerger-#2]
Hello
Thanks for your updates man, but when will you add the feature to delete a contact.
Regards
/M

**Comment by moh1122** [comment]
hello 
can you give me a clue and  can work on it.
As i need i very urgently.
Thank you

**Comment by geowarsong** [comment]
Hello, Sorry for the late answer because i have lot of staff to do in this week. I will post a snippet of code which is doing all the stuff actually.

ABRecordRef delete = ABAddressBookGetPersonWithRecordID(_addressBook, IDContact);
ABAddressBookRemoveRecord(_addressBook, delete, &error);

For ABAddressBookRemoveRecord first argument should be a person which you want to delete from address book. For more information please have a look to this links:

1) http://stackoverflow.com/questions/10621901/is-this-the-right-way-to-delete-a-contact-from-the-iphone
2) http://iphonedevsdk.com/forum/iphone-sdk-development/62069-is-it-possible-to-delete-contacts-records-using-abaddressbook.html

**Comment by moh1122** [comment]
hello
thnks for your reply but the links you sent are in obj c 
ad wht u wrote is not working with me
can you help plz coz its your code and i cant make it 
thank you
